package conversordivisasnet;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

public class MenuPrincipal extends javax.swing.JFrame {
    
    public ConversorDivisas cd;
    public ConversorTemperaturas ct;

    public MenuPrincipal() {
        initComponents();
        this.setTitle("Conversor Unidades");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/mundo.png"));
        this.setIconImage(icono);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);          
    }
    
    void cargaDivisas(){
        if(cd == null || cd.isActive()){
            cd = new ConversorDivisas();
            cd.setVisible(rootPaneCheckingEnabled);
        }
    }
    
    void cargaTemperaturas(){
        if(ct == null || ct.isActive()){
            ct = new ConversorTemperaturas();
            ct.setVisible(rootPaneCheckingEnabled);
        }
    }
    
    public void Cerrar(){
        String botones[] = {"Cerrar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(this, "¿Desea cerrar la aplicacion?", 
                "Cierre", 0, 0, null, botones, this);
        if(eleccion == JOptionPane.YES_OPTION){
            System.exit(0);
        }else if(eleccion == JOptionPane.NO_OPTION){
            System.out.println("Se cancela el cierre");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleMenu = new javax.swing.JLabel();
        secondTitleMenu = new javax.swing.JLabel();
        changeButton = new javax.swing.JButton();
        temperaturesButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        byText = new javax.swing.JLabel();
        linkedinLink = new javax.swing.JLabel();
        githubLink = new javax.swing.JLabel();
        backGroundMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleMenu.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        titleMenu.setForeground(new java.awt.Color(0, 0, 0));
        titleMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleMenu.setText("CONVERSOR");
        titleMenu.setToolTipText("");
        titleMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(titleMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 330, 50));

        secondTitleMenu.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        secondTitleMenu.setForeground(new java.awt.Color(0, 0, 0));
        secondTitleMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondTitleMenu.setText("DE UNIDADES");
        jPanel1.add(secondTitleMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 320, -1));

        changeButton.setBackground(new java.awt.Color(102, 153, 0));
        changeButton.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        changeButton.setForeground(new java.awt.Color(0, 0, 0));
        changeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RupiaZelda.png"))); // NOI18N
        changeButton.setText("  DIVISAS");
        changeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeButton.setDefaultCapable(false);
        changeButton.setMaximumSize(new java.awt.Dimension(113, 28));
        changeButton.setMinimumSize(new java.awt.Dimension(113, 28));
        changeButton.setPreferredSize(new java.awt.Dimension(113, 28));
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(changeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 270, 80));

        temperaturesButton.setBackground(new java.awt.Color(102, 153, 0));
        temperaturesButton.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        temperaturesButton.setForeground(new java.awt.Color(0, 0, 0));
        temperaturesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MedallonFuego.png"))); // NOI18N
        temperaturesButton.setText("  TEMPERATURAS");
        temperaturesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        temperaturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperaturesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(temperaturesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 270, 80));

        jButton1.setBackground(new java.awt.Color(102, 153, 0));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("PROXIMAMENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 270, 80));

        byText.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        byText.setForeground(new java.awt.Color(255, 255, 255));
        byText.setText("Creador por: Jose Eduardo Rodriguez Antunez");
        jPanel1.add(byText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, 30));

        linkedinLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linkedin64.png"))); // NOI18N
        linkedinLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkedinLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkedinLinkMouseClicked(evt);
            }
        });
        jPanel1.add(linkedinLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, -1, 70));

        githubLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/github 64px.png"))); // NOI18N
        githubLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        githubLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                githubLinkMouseClicked(evt);
            }
        });
        jPanel1.add(githubLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 655, -1, -1));

        backGroundMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoMenuPrincipal.jpg"))); // NOI18N
        jPanel1.add(backGroundMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-440, 0, 920, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        cargaDivisas();
    }//GEN-LAST:event_changeButtonActionPerformed

    private void temperaturesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperaturesButtonActionPerformed
        cargaTemperaturas();
    }//GEN-LAST:event_temperaturesButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void linkedinLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedinLinkMouseClicked
        
        if(java.awt.Desktop.isDesktopSupported()){
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            
            if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
                try{
                    java.net.URI uri = new java.net.URI("https://www.linkedin.com/in/jose-eduardo-rodriguez-antunez/");
                    desktop.browse(uri);
                } catch(URISyntaxException | IOException ex) {}
            }
        }
    }//GEN-LAST:event_linkedinLinkMouseClicked

    private void githubLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_githubLinkMouseClicked
        
        if(java.awt.Desktop.isDesktopSupported()){
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            
            if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
                try{
                    java.net.URI uri = new java.net.URI("https://github.com/MiumaVT");
                    desktop.browse(uri);
                } catch(URISyntaxException | IOException ex) {}
            }
        }
    }//GEN-LAST:event_githubLinkMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGroundMenu;
    private javax.swing.JLabel byText;
    private javax.swing.JButton changeButton;
    private javax.swing.JLabel githubLink;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel linkedinLink;
    private javax.swing.JLabel secondTitleMenu;
    private javax.swing.JButton temperaturesButton;
    private javax.swing.JLabel titleMenu;
    // End of variables declaration//GEN-END:variables
}
